### PR TITLE
Migrate to standard Haskell project structure

### PR DESCRIPTION
**Pull request by spinda**
Adding the necessary files to make Hasklate build with Cabal
or Stack.

### CODE REVIEW

**Comment by spinda** [comment]
I wasn't sure what to set for the "license" field of the .cabal file, so I left that out. Some tools might complain about that.

**Comment by Ekleog** [comment]
Looks good, thanks!

Just a two things:
- I just added a license file, could you rebase on top of it to show you agree with it?
- I don't actually feel good about adding a generated file to the repository with no automation means to make sure it is up-to-date when committing -- and as a consequence I wonder if it's actually useful to put one in. I've checked a syntax prettifier in haskell and it didn't put an example in. Do you actually think it's a good idea?

**Comment by spinda** [comment]
Done!

**Comment by Ekleog** [comment]
Merged, thanks! :)

**Pull request merged**
